TARGET=MojiGene.exe
OBJ = rng.obj utf8_table.obj utf8.obj MojiGene.obj
CFLAGS = -bt=nt -c
LFLAGS = -l=nt
CC=wcl386

all: $(TARGET)

rng.obj: rng.c
	$(CC) $(CFLAGS) -fo=$@ $<

utf8_table.obj: utf8_table.c
	$(CC) $(CFLAGS) -fo=$@ $<

utf8.obj: utf8.c
	$(CC) $(CFLAGS) -fo=$@ $<

MojiGene.obj: MojiGene.c
	$(CC) $(CFLAGS) -fo=$@ $<

$(TARGET): $(OBJ)
	$(CC) $(LFLAGS) -fe=$@ $(OBJ)

clean:
	rm -f $(TARGET) $(OBJ) *.err
