TARGET=MojiGene.exe
OBJ = MojiGene.obj
CFLAGS = -bt=nt -c
LFLAGS = -l=nt
CC=wcl386


all: $(TARGET)

MojiGene.obj: MojiGene.c
	$(CC) $(CFLAGS) -fo=$@ $<

$(TARGET): $(OBJ)
	$(CC) $(LFLAGS) -fe=$@ $(OBJ)

clean:
	rm -f $(TARGET) $(OBJ)
